# © 2023 The mhfz-overlay developers.
# Use of this source code is governed by a MIT license that can be
# found in the LICENSE file.

source 'https://rubygems.org'

gem 'rake'
gem 'rmagick'
gem 'gruff'