# frozen_string_literal = true
# © 2023 The mhfz-overlay developers.
# Use of this source code is governed by a MIT license that can be
# found in the LICENSE file.

task default: %w[generate_images]

task :generate_images do
  Dir.chdir('..') do
    ruby 'commits_over_time.rb'
    ruby 'commits_type_count.rb'
  end
end
