name: "🐛 Bug Report"
description: File a bug report
title: "[BUG]: - <title>"
labels: ["bug"]
assignees:
  - DorielRivalet
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: What version of the program are you using?
      description: Program Version
      placeholder: Tell us what version you using
      value: "Latest version"
    validations:
      required: true
  - type: dropdown
    id: game-version
    attributes:
      label: What version of the game are you using?
      multiple: true
      options:
        - High-Grade Edition
        - Non High-Grade Edition