name: "🐛 Bug Report"
description: File a bug report
title: "[BUG] - title"
labels: ["bug"]
assignees:
  - DorielRivalet
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? Please drag and drop the log file below, you can find it in the overlay folder, inside the log folder. If possible, add instructions on how to reproduce the bug. The logs folder is found in C:\Users\NAME\AppData\Local\MHFZ_Overlay\app-x.y.z\logs.
      placeholder: Tell us what you see!
      value: "A bug happened! Here is my crash log"
    validations:
      required: true
  - type: dropdown
    id: bug-frequency
    attributes:
      label: How often does the bug occur?
      multiple: false
      options:
        - Rarely
        - Sometimes
        - Always
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: What version of the program are you using?
      description: Program Version
      placeholder: Tell us what version you are using (x.y.z)
      value: "Latest version"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!