name: "🐛 Bug Report"
description: File a bug report
title: "[BUG] - title"
labels: ["bug"]
assignees:
  - DorielRivalet
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen? Please add the crash log or log file information if you have them, you can find them in the overlay folder and in the game\database folder. If possible, add instructions on how to reproduce the bug.
      placeholder: Tell us what you see!
      value: "A bug happened! Here is my crash log"
    validations:
      required: true
  - type: dropdown
    id: bug-frequency
    attributes:
      label: How often does the bug occur?
      multiple: false
      options:
        - Rarely
        - Sometimes
        - Always
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: What version of the program are you using?
      description: Program Version
      placeholder: Tell us what version you using (x.y.z)
      value: "Latest version"
    validations:
      required: true
  - type: dropdown
    id: game-version
    attributes:
      label: What version of the game are you using?
      multiple: true
      options:
        - High-Grade Edition
        - Non High-Grade Edition
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!