name: "💡 Feature Request"
description: Create a new ticket for a new feature request
title: "[REQUEST] - <title>"
labels: [
  "question",
  "enhancement"
]
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your feature.
      value: |
        ![DESCRIPTION](LINK.png)
      render: bash
    validations:
      required: false