name: "💡 Feature Request"
description: Create a new ticket for a new feature request
title: "[REQUEST] - title"
labels: [
  "question",
  "enhancement"
]
assignees:
  - DorielRivalet
body:
  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: Provide a brief explanation of the feature
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!