using MHFZ_Overlay;
using System.Collections.Generic;
using System.Diagnostics.Metrics;
using System.Security.Policy;
using System.Windows.Documents;
using System.Windows.Media;
using System.Windows.Navigation;

namespace Dictionary
{
    ///<summary>
    ///The monster image list
    ///</summary>
    public static class MonsterImage
    {
        public static IReadOnlyDictionary<int, string> MonsterImageID { get; } = new Dictionary<int, string>
        {
            {0, "https://i.imgur.com/3pQEtzw.png"},
            {1, "https://i.imgur.com/uW1PHeW.png"},
            { 3, "https://i.imgur.com/Ad5xCF6.png"},
            { 4,"https://i.imgur.com/qWSVddC.png"},
            { 5,"https://i.imgur.com/qz7CynW.png"},
            { 6,"https://i.imgur.com/TtJ7KPw.png"},
            { 7,"https://i.imgur.com/ZW43PS5.png"},
            { 8,"https://i.imgur.com/RwkhTLJ.png"},
            { 9,"https://i.imgur.com/Ry2zu5r.png"},
            { 10,"https://i.imgur.com/3pQEtzw.png"},
            { 12,"https://i.imgur.com/15KEndF.png"},
            { 13,"https://i.imgur.com/ChQomJ4.png"},
            { 14,"https://i.imgur.com/XZaYYFL.png"},
            { 16,"https://i.imgur.com/WGrl1DY.png"},
            { 18,"https://i.imgur.com/Ry2zu5r.png"},
            { 19,"https://i.imgur.com/dhiIvMc.png"},
            { 20,"https://i.imgur.com/vovKgVw.png"},
            { 22,"https://i.imgur.com/y86jUp6.png"},
            { 23,"https://i.imgur.com/LoqmciT.png"},
            { 24,"https://i.imgur.com/uXam7c6.png"},
            { 25,"https://i.imgur.com/Y2ovscJ.png"},
            { 26,"https://i.imgur.com/bJt02Qe.png"},
            { 27,"https://i.imgur.com/6HMWaGt.png"},
            { 28,"https://i.imgur.com/XBWX8Wm.png"},
            { 29,"https://i.imgur.com/3pQEtzw.png"},
            { 30,"https://i.imgur.com/KDxPzPs.png"},
            { 31,"https://i.imgur.com/QsyXEmc.png"},
            { 32,"https://i.imgur.com/3pQEtzw.png"},
            { 33,"https://i.imgur.com/5s4ToRS.png"},
            { 34,"https://i.imgur.com/3n7NQG9.png"},
            { 35,"https://i.imgur.com/QPl1AEF.png"},
            { 37,"https://i.imgur.com/yn3uMc2.png"},
            { 38,"https://i.imgur.com/NmRxU2H.png"},
            { 39,"https://i.imgur.com/eDiBAxX.png"},
            { 40,"https://i.imgur.com/ApZmoUv.png"},
            { 41,"https://i.imgur.com/mYY8y19.png"},
            { 42,"https://i.imgur.com/xe8nLNM.png"},
            { 43,"https://i.imgur.com/IVXcxRD.png"},
            { 44,"https://i.imgur.com/BQ9FJBB.png"},
            { 45,"https://i.imgur.com/Cmb6AYd.png"},
            { 46,"https://i.imgur.com/LQnA7d6.png"},
            { 47,"https://i.imgur.com/Fmw5Etb.png"},
            { 49,"https://i.imgur.com/gSCligX.png"},
            { 50,"https://i.imgur.com/fHPx16u.png"},
            { 52,"https://i.imgur.com/qxaMV1h.png"},
            { 54,"https://i.imgur.com/uAyaJ9z.png"},
            { 55,"https://i.imgur.com/pgKJuGj.png"},
            { 56,"https://i.imgur.com/u0M5jXA.png"},
            { 57,"https://i.imgur.com/UaZkOgY.png"},
            { 58,"https://i.imgur.com/suHOj84.png"},
            { 59,"https://i.imgur.com/TXmNN2X.png"},
            { 60,"https://i.imgur.com/4hNQwSU.png"},
            { 61,"https://i.imgur.com/3hBdp8b.png"},
            { 62,"https://i.imgur.com/zxQcbQD.png"},
            { 63,"https://i.imgur.com/kewyYlK.png"},
            { 64,"https://i.imgur.com/8OvYfy6.png"},
            { 66,"https://i.imgur.com/l2SOZee.png"},
            { 67,"https://i.imgur.com/lEcEWZ6.png"},
            { 68,"https://i.imgur.com/AxBWXBC.png"},
            { 69,"https://i.imgur.com/QxGg3Np.png"},
            { 70,"https://i.imgur.com/jTFVi1A.png"},
            { 72,"https://i.imgur.com/suHOj84.png"},
            { 73,"https://i.imgur.com/2PbL0oE.png"},
            { 74,"https://i.imgur.com/tkYXFBc.png"},
            { 75,"https://i.imgur.com/ZSgmzGi.png"},
            { 77,"https://i.imgur.com/CKY7zkV.png"},
            { 78,"https://i.imgur.com/fhF6yZY.png"},
            { 79,"https://i.imgur.com/AzfTTSq.png"},
            { 81,"https://i.imgur.com/m8DhwiJ.png"},
            { 82,"https://i.imgur.com/WZkQYDL.png"},
            { 84,"https://i.imgur.com/hOfRrph.png"},
            { 85,"https://i.imgur.com/KBCnVhH.png"},
            { 86,"https://i.imgur.com/3pQEtzw.png"},
            { 87,"https://i.imgur.com/3pQEtzw.png"},
            { 88,"https://i.imgur.com/3pQEtzw.png"},
            { 90,"https://i.imgur.com/Uc5mTQi.png"},
            { 91,"https://i.imgur.com/L9naUDO.png"},
            { 92,"https://i.imgur.com/klyXxuc.png"},
            { 93,"https://i.imgur.com/blsy8Rx.png"},
            { 94,"https://i.imgur.com/dxEtSjL.png"},
            { 96,"https://i.imgur.com/gLA5gdi.png"},
            { 97,"https://i.imgur.com/6RIoFpM.png"},
            { 98,"https://i.imgur.com/R3xnyMd.png"},
            { 101, "https://i.imgur.com/HBYZoa0.png"},
            { 102, "https://i.imgur.com/HBYZoa0.png"},
            { 104, "https://i.imgur.com/dxkeQcm.png"},
            { 105, "https://i.imgur.com/PqTQLGE.png"},
            { 108, "https://i.imgur.com/fdFZFKe.png"},
            { 114, "https://i.imgur.com/cBHzq5t.png"},
            { 115, "https://i.imgur.com/OpYh7mb.png"},
            { 117, "https://i.imgur.com/jaKE3QM.png"},
            { 118,"https://i.imgur.com/3pQEtzw.png"},
            { 119, "https://i.imgur.com/jwR2xoG.png"},
            { 120, "https://i.imgur.com/d9K9HlH.png"},
            { 122,  "https://i.imgur.com/XOEGJRu.png"},
            { 123, "https://i.imgur.com/0TeOdn4.png"},
            { 124, "https://i.imgur.com/fQPpwGE.png"},
            { 125, "https://i.imgur.com/p7LWhIe.png"},
            { 126, "https://i.imgur.com/iQMDmCN.png"},
            { 127, "https://i.imgur.com/4zi1Kva.png"},
            { 128, "https://i.imgur.com/NHyezpo.png"},
            { 130, "https://i.imgur.com/KXLFD8f.png"},
            { 131, "https://i.imgur.com/56tHHHc.png"},
            { 132, "https://i.imgur.com/fKVoJ3m.png"},
            { 133, "https://i.imgur.com/3pQEtzw.png"},
            { 134, "https://i.imgur.com/Ry2zu5r.png"},
            { 135, "https://i.imgur.com/3pQEtzw.png"},
            { 136, "https://i.imgur.com/3pQEtzw.png"},
            { 137, "https://i.imgur.com/3pQEtzw.png"},
            { 138, "https://i.imgur.com/3pQEtzw.png"},
            { 139, "https://i.imgur.com/JntsUFx.png"},
            { 143, "https://i.imgur.com/EMWA1p7.png"},
            { 144, "https://i.imgur.com/qy7yTjz.png"},
            { 145, "https://i.imgur.com/fKVoJ3m.png"},
            { 147, "https://i.imgur.com/eGsb66E.png"},
            { 148, "https://i.imgur.com/XrYCP6k.png"},
            { 149, "https://i.imgur.com/HDkGUQL.png"},
            { 150, "https://i.imgur.com/muRi2Yz.png"},
            { 151, "https://i.imgur.com/OE88eb9.png"},
            { 152, "https://i.imgur.com/K3vqmPA.png"},
            { 153, "https://i.imgur.com/oz11SGA.png"},
            { 156, "https://i.imgur.com/3pQEtzw.png"},
            { 157, "https://i.imgur.com/3pQEtzw.png"},
            { 158, "https://i.imgur.com/WgzdVtV.png"},
            { 159, "https://i.imgur.com/Xi9lXsZ.png"},
            { 160, "https://i.imgur.com/tHCL5U3.png"},
            { 161, "https://i.imgur.com/cLOEjlO.png"},
            { 162, "https://i.imgur.com/Lq6kNtM.png"},
            { 163, "https://i.imgur.com/ossvc1M.png"},
            { 164, "https://i.imgur.com/15V9po1.png"},
            { 165, "https://i.imgur.com/z5E7rSP.png"},
            { 167, "https://i.imgur.com/HrSImCm.png"},
            { 168, "https://i.imgur.com/3pQEtzw.png"},
            { 169, "https://i.imgur.com/BEeL8xd.png"},
            { 170, "https://i.imgur.com/tbV6QPE.gif"},
            { 171, "https://i.imgur.com/3pQEtzw.png"},
            { 172, "https://i.imgur.com/vd6Y06a.png"},
            { 173, "https://i.imgur.com/fQPpwGE.png"},
            { 174, "https://i.imgur.com/3c8kwQD.png"},
            { 175, "https://i.imgur.com/3pQEtzw.png"},
            { 176, "https://i.imgur.com/UXi0TEu.png"},
        };
    }
}