//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHFZ_Overlay {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableDamageNumbers {
            get {
                return ((bool)(this["EnableDamageNumbers"]));
            }
            set {
                this["EnableDamageNumbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int IsRoadOverride {
            get {
                return ((int)(this["IsRoadOverride"]));
            }
            set {
                this["IsRoadOverride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysShowMonsterInfo {
            get {
                return ((bool)(this["AlwaysShowMonsterInfo"]));
            }
            set {
                this["AlwaysShowMonsterInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#f38ba8")]
        public string Monster1BarColor {
            get {
                return ((string)(this["Monster1BarColor"]));
            }
            set {
                this["Monster1BarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#f38ba8")]
        public string Monster2BarColor {
            get {
                return ((string)(this["Monster2BarColor"]));
            }
            set {
                this["Monster2BarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#f38ba8")]
        public string Monster3BarColor {
            get {
                return ((string)(this["Monster3BarColor"]));
            }
            set {
                this["Monster3BarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#f38ba8")]
        public string Monster4BarColor {
            get {
                return ((string)(this["Monster4BarColor"]));
            }
            set {
                this["Monster4BarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#cba6f7")]
        public string MonsterPoisonBarColor {
            get {
                return ((string)(this["MonsterPoisonBarColor"]));
            }
            set {
                this["MonsterPoisonBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#fab387")]
        public string MonsterBlastBarColor {
            get {
                return ((string)(this["MonsterBlastBarColor"]));
            }
            set {
                this["MonsterBlastBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#74c7ec")]
        public string MonsterSleepBarColor {
            get {
                return ((string)(this["MonsterSleepBarColor"]));
            }
            set {
                this["MonsterSleepBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#f9e2af")]
        public string MonsterParaBarColor {
            get {
                return ((string)(this["MonsterParaBarColor"]));
            }
            set {
                this["MonsterParaBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#7f849c")]
        public string MonsterStunBarColor {
            get {
                return ((string)(this["MonsterStunBarColor"]));
            }
            set {
                this["MonsterStunBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public string HPBackGroundColor {
            get {
                return ((string)(this["HPBackGroundColor"]));
            }
            set {
                this["HPBackGroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public string TextBackGroundColor {
            get {
                return ((string)(this["TextBackGroundColor"]));
            }
            set {
                this["TextBackGroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#f5e0dc")]
        public string TextColor {
            get {
                return ((string)(this["TextColor"]));
            }
            set {
                this["TextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("840")]
        public double HealthBarsX {
            get {
                return ((double)(this["HealthBarsX"]));
            }
            set {
                this["HealthBarsX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("36")]
        public double HealthBarsY {
            get {
                return ((double)(this["HealthBarsY"]));
            }
            set {
                this["HealthBarsY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HealthBarsShown {
            get {
                return ((bool)(this["HealthBarsShown"]));
            }
            set {
                this["HealthBarsShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double PlayerInfoX {
            get {
                return ((double)(this["PlayerInfoX"]));
            }
            set {
                this["PlayerInfoX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("358")]
        public double PlayerInfoY {
            get {
                return ((double)(this["PlayerInfoY"]));
            }
            set {
                this["PlayerInfoY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlayerInfoShown {
            get {
                return ((bool)(this["PlayerInfoShown"]));
            }
            set {
                this["PlayerInfoShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1087")]
        public double MonsterStatusInfoX {
            get {
                return ((double)(this["MonsterStatusInfoX"]));
            }
            set {
                this["MonsterStatusInfoX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("207")]
        public double MonsterStatusInfoY {
            get {
                return ((double)(this["MonsterStatusInfoY"]));
            }
            set {
                this["MonsterStatusInfoY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MonsterStatusInfoShown {
            get {
                return ((bool)(this["MonsterStatusInfoShown"]));
            }
            set {
                this["MonsterStatusInfoShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int FontSize {
            get {
                return ((int)(this["FontSize"]));
            }
            set {
                this["FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableDamageNumbersMulticolor {
            get {
                return ((bool)(this["EnableDamageNumbersMulticolor"]));
            }
            set {
                this["EnableDamageNumbersMulticolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableEHPNumbers {
            get {
                return ((bool)(this["EnableEHPNumbers"]));
            }
            set {
                this["EnableEHPNumbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableRichPresence {
            get {
                return ((bool)(this["EnableRichPresence"]));
            }
            set {
                this["EnableRichPresence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string DiscordClientID {
            get {
                return ((string)(this["DiscordClientID"]));
            }
            set {
                this["DiscordClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\"")]
        public string DiscordServerInvite {
            get {
                return ((string)(this["DiscordServerInvite"]));
            }
            set {
                this["DiscordServerInvite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableCurrentHPPercentage {
            get {
                return ((bool)(this["EnableCurrentHPPercentage"]));
            }
            set {
                this["EnableCurrentHPPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableTimeLeftPercentage {
            get {
                return ((bool)(this["EnableTimeLeftPercentage"]));
            }
            set {
                this["EnableTimeLeftPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#fffab387")]
        public string DamageNumbersColor {
            get {
                return ((string)(this["DamageNumbersColor"]));
            }
            set {
                this["DamageNumbersColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableSharpness {
            get {
                return ((bool)(this["EnableSharpness"]));
            }
            set {
                this["EnableSharpness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("140")]
        public double SharpnessInfoY {
            get {
                return ((double)(this["SharpnessInfoY"]));
            }
            set {
                this["SharpnessInfoY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public double SharpnessInfoX {
            get {
                return ((double)(this["SharpnessInfoX"]));
            }
            set {
                this["SharpnessInfoX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PartHealthBarsShown {
            get {
                return ((bool)(this["PartHealthBarsShown"]));
            }
            set {
                this["PartHealthBarsShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("925")]
        public double PartBarsX {
            get {
                return ((double)(this["PartBarsX"]));
            }
            set {
                this["PartBarsX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("425")]
        public double PartBarsY {
            get {
                return ((double)(this["PartBarsY"]));
            }
            set {
                this["PartBarsY"] = value;
            }
        }
    }
}
