//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHFZ_Overlay {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.3.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableDamageNumbers {
            get {
                return ((bool)(this["EnableDamageNumbers"]));
            }
            set {
                this["EnableDamageNumbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int IsRoadOverride {
            get {
                return ((int)(this["IsRoadOverride"]));
            }
            set {
                this["IsRoadOverride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AlwaysShowMonsterInfo {
            get {
                return ((bool)(this["AlwaysShowMonsterInfo"]));
            }
            set {
                this["AlwaysShowMonsterInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#f38ba8")]
        public string Monster1BarColor {
            get {
                return ((string)(this["Monster1BarColor"]));
            }
            set {
                this["Monster1BarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#f38ba8")]
        public string Monster2BarColor {
            get {
                return ((string)(this["Monster2BarColor"]));
            }
            set {
                this["Monster2BarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#f38ba8")]
        public string Monster3BarColor {
            get {
                return ((string)(this["Monster3BarColor"]));
            }
            set {
                this["Monster3BarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#f38ba8")]
        public string Monster4BarColor {
            get {
                return ((string)(this["Monster4BarColor"]));
            }
            set {
                this["Monster4BarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#cba6f7")]
        public string MonsterPoisonBarColor {
            get {
                return ((string)(this["MonsterPoisonBarColor"]));
            }
            set {
                this["MonsterPoisonBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#a6e3a1")]
        public string MonsterBlastBarColor {
            get {
                return ((string)(this["MonsterBlastBarColor"]));
            }
            set {
                this["MonsterBlastBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#74c7ec")]
        public string MonsterSleepBarColor {
            get {
                return ((string)(this["MonsterSleepBarColor"]));
            }
            set {
                this["MonsterSleepBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#f9e2af")]
        public string MonsterParaBarColor {
            get {
                return ((string)(this["MonsterParaBarColor"]));
            }
            set {
                this["MonsterParaBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#7f849c")]
        public string MonsterStunBarColor {
            get {
                return ((string)(this["MonsterStunBarColor"]));
            }
            set {
                this["MonsterStunBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public string HPBackGroundColor {
            get {
                return ((string)(this["HPBackGroundColor"]));
            }
            set {
                this["HPBackGroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Transparent")]
        public string TextBackGroundColor {
            get {
                return ((string)(this["TextBackGroundColor"]));
            }
            set {
                this["TextBackGroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#f5e0dc")]
        public string TextColor {
            get {
                return ((string)(this["TextColor"]));
            }
            set {
                this["TextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("831")]
        public double HealthBarsX {
            get {
                return ((double)(this["HealthBarsX"]));
            }
            set {
                this["HealthBarsX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("33")]
        public double HealthBarsY {
            get {
                return ((double)(this["HealthBarsY"]));
            }
            set {
                this["HealthBarsY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HealthBarsShown {
            get {
                return ((bool)(this["HealthBarsShown"]));
            }
            set {
                this["HealthBarsShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public double PlayerInfoX {
            get {
                return ((double)(this["PlayerInfoX"]));
            }
            set {
                this["PlayerInfoX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("358")]
        public double PlayerInfoY {
            get {
                return ((double)(this["PlayerInfoY"]));
            }
            set {
                this["PlayerInfoY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlayerInfoShown {
            get {
                return ((bool)(this["PlayerInfoShown"]));
            }
            set {
                this["PlayerInfoShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1087")]
        public double MonsterStatusInfoX {
            get {
                return ((double)(this["MonsterStatusInfoX"]));
            }
            set {
                this["MonsterStatusInfoX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("188")]
        public double MonsterStatusInfoY {
            get {
                return ((double)(this["MonsterStatusInfoY"]));
            }
            set {
                this["MonsterStatusInfoY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MonsterStatusInfoShown {
            get {
                return ((bool)(this["MonsterStatusInfoShown"]));
            }
            set {
                this["MonsterStatusInfoShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public int FontSize {
            get {
                return ((int)(this["FontSize"]));
            }
            set {
                this["FontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableDamageNumbersMulticolor {
            get {
                return ((bool)(this["EnableDamageNumbersMulticolor"]));
            }
            set {
                this["EnableDamageNumbersMulticolor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableEHPNumbers {
            get {
                return ((bool)(this["EnableEHPNumbers"]));
            }
            set {
                this["EnableEHPNumbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableRichPresence {
            get {
                return ((bool)(this["EnableRichPresence"]));
            }
            set {
                this["EnableRichPresence"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DiscordClientID {
            get {
                return ((string)(this["DiscordClientID"]));
            }
            set {
                this["DiscordClientID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DiscordServerInvite {
            get {
                return ((string)(this["DiscordServerInvite"]));
            }
            set {
                this["DiscordServerInvite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableCurrentHPPercentage {
            get {
                return ((bool)(this["EnableCurrentHPPercentage"]));
            }
            set {
                this["EnableCurrentHPPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableTimeLeftPercentage {
            get {
                return ((bool)(this["EnableTimeLeftPercentage"]));
            }
            set {
                this["EnableTimeLeftPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#fffab387")]
        public string DamageNumbersColor {
            get {
                return ((string)(this["DamageNumbersColor"]));
            }
            set {
                this["DamageNumbersColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableSharpness {
            get {
                return ((bool)(this["EnableSharpness"]));
            }
            set {
                this["EnableSharpness"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("105")]
        public double SharpnessInfoX {
            get {
                return ((double)(this["SharpnessInfoX"]));
            }
            set {
                this["SharpnessInfoX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("62")]
        public double SharpnessInfoY {
            get {
                return ((double)(this["SharpnessInfoY"]));
            }
            set {
                this["SharpnessInfoY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PartThresholdShown {
            get {
                return ((bool)(this["PartThresholdShown"]));
            }
            set {
                this["PartThresholdShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double Monster1PartX {
            get {
                return ((double)(this["Monster1PartX"]));
            }
            set {
                this["Monster1PartX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("685")]
        public double Monster1PartY {
            get {
                return ((double)(this["Monster1PartY"]));
            }
            set {
                this["Monster1PartY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AlwaysShowPlayerInfo {
            get {
                return ((bool)(this["AlwaysShowPlayerInfo"]));
            }
            set {
                this["AlwaysShowPlayerInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableSharpnessPercentage {
            get {
                return ((bool)(this["EnableSharpnessPercentage"]));
            }
            set {
                this["EnableSharpnessPercentage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HunterName")]
        public string HunterName {
            get {
                return ((string)(this["HunterName"]));
            }
            set {
                this["HunterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GuildName")]
        public string GuildName {
            get {
                return ((string)(this["GuildName"]));
            }
            set {
                this["GuildName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TimerInfoShown {
            get {
                return ((bool)(this["TimerInfoShown"]));
            }
            set {
                this["TimerInfoShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double TimerX {
            get {
                return ((double)(this["TimerX"]));
            }
            set {
                this["TimerX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("560")]
        public double TimerY {
            get {
                return ((double)(this["TimerY"]));
            }
            set {
                this["TimerY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HitCountShown {
            get {
                return ((bool)(this["HitCountShown"]));
            }
            set {
                this["HitCountShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double HitCountX {
            get {
                return ((double)(this["HitCountX"]));
            }
            set {
                this["HitCountX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double HitCountY {
            get {
                return ((double)(this["HitCountY"]));
            }
            set {
                this["HitCountY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlayerAtkShown {
            get {
                return ((bool)(this["PlayerAtkShown"]));
            }
            set {
                this["PlayerAtkShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double PlayerAtkX {
            get {
                return ((double)(this["PlayerAtkX"]));
            }
            set {
                this["PlayerAtkX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("640")]
        public double PlayerAtkY {
            get {
                return ((double)(this["PlayerAtkY"]));
            }
            set {
                this["PlayerAtkY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Time Left")]
        public string TimerMode {
            get {
                return ((string)(this["TimerMode"]));
            }
            set {
                this["TimerMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MonsterAtkMultShown {
            get {
                return ((bool)(this["MonsterAtkMultShown"]));
            }
            set {
                this["MonsterAtkMultShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1060")]
        public double MonsterAtkMultX {
            get {
                return ((double)(this["MonsterAtkMultX"]));
            }
            set {
                this["MonsterAtkMultX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public double MonsterAtkMultY {
            get {
                return ((double)(this["MonsterAtkMultY"]));
            }
            set {
                this["MonsterAtkMultY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MonsterDefrateShown {
            get {
                return ((bool)(this["MonsterDefrateShown"]));
            }
            set {
                this["MonsterDefrateShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1060")]
        public double MonsterDefrateX {
            get {
                return ((double)(this["MonsterDefrateX"]));
            }
            set {
                this["MonsterDefrateX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230")]
        public double MonsterDefrateY {
            get {
                return ((double)(this["MonsterDefrateY"]));
            }
            set {
                this["MonsterDefrateY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MonsterSizeShown {
            get {
                return ((bool)(this["MonsterSizeShown"]));
            }
            set {
                this["MonsterSizeShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1060")]
        public double MonsterSizeX {
            get {
                return ((double)(this["MonsterSizeX"]));
            }
            set {
                this["MonsterSizeX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("260")]
        public double MonsterSizeY {
            get {
                return ((double)(this["MonsterSizeY"]));
            }
            set {
                this["MonsterSizeY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MonsterPoisonShown {
            get {
                return ((bool)(this["MonsterPoisonShown"]));
            }
            set {
                this["MonsterPoisonShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1060")]
        public double MonsterPoisonX {
            get {
                return ((double)(this["MonsterPoisonX"]));
            }
            set {
                this["MonsterPoisonX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double MonsterPoisonY {
            get {
                return ((double)(this["MonsterPoisonY"]));
            }
            set {
                this["MonsterPoisonY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MonsterSleepShown {
            get {
                return ((bool)(this["MonsterSleepShown"]));
            }
            set {
                this["MonsterSleepShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1060")]
        public double MonsterSleepX {
            get {
                return ((double)(this["MonsterSleepX"]));
            }
            set {
                this["MonsterSleepX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("330")]
        public double MonsterSleepY {
            get {
                return ((double)(this["MonsterSleepY"]));
            }
            set {
                this["MonsterSleepY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MonsterParaShown {
            get {
                return ((bool)(this["MonsterParaShown"]));
            }
            set {
                this["MonsterParaShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1060")]
        public double MonsterParaX {
            get {
                return ((double)(this["MonsterParaX"]));
            }
            set {
                this["MonsterParaX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("360")]
        public double MonsterParaY {
            get {
                return ((double)(this["MonsterParaY"]));
            }
            set {
                this["MonsterParaY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MonsterBlastShown {
            get {
                return ((bool)(this["MonsterBlastShown"]));
            }
            set {
                this["MonsterBlastShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1060")]
        public double MonsterBlastX {
            get {
                return ((double)(this["MonsterBlastX"]));
            }
            set {
                this["MonsterBlastX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("390")]
        public double MonsterBlastY {
            get {
                return ((double)(this["MonsterBlastY"]));
            }
            set {
                this["MonsterBlastY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MonsterStunShown {
            get {
                return ((bool)(this["MonsterStunShown"]));
            }
            set {
                this["MonsterStunShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1060")]
        public double MonsterStunX {
            get {
                return ((double)(this["MonsterStunX"]));
            }
            set {
                this["MonsterStunX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("420")]
        public double MonsterStunY {
            get {
                return ((double)(this["MonsterStunY"]));
            }
            set {
                this["MonsterStunY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public double DamageNumbersX {
            get {
                return ((double)(this["DamageNumbersX"]));
            }
            set {
                this["DamageNumbersX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public double DamageNumbersY {
            get {
                return ((double)(this["DamageNumbersY"]));
            }
            set {
                this["DamageNumbersY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double DamageNumbersAreaWidth {
            get {
                return ((double)(this["DamageNumbersAreaWidth"]));
            }
            set {
                this["DamageNumbersAreaWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public double DamageNumbersAreaHeight {
            get {
                return ((double)(this["DamageNumbersAreaHeight"]));
            }
            set {
                this["DamageNumbersAreaHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableHighestAtkColor {
            get {
                return ((bool)(this["EnableHighestAtkColor"]));
            }
            set {
                this["EnableHighestAtkColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Monster1IconShown {
            get {
                return ((bool)(this["Monster1IconShown"]));
            }
            set {
                this["Monster1IconShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public double Monster1IconX {
            get {
                return ((double)(this["Monster1IconX"]));
            }
            set {
                this["Monster1IconX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("470")]
        public double Monster1IconY {
            get {
                return ((double)(this["Monster1IconY"]));
            }
            set {
                this["Monster1IconY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Time Left")]
        public string DiscordTimerMode {
            get {
                return ((string)(this["DiscordTimerMode"]));
            }
            set {
                this["DiscordTimerMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Never")]
        public string DiscordRoadTimerReset {
            get {
                return ((string)(this["DiscordRoadTimerReset"]));
            }
            set {
                this["DiscordRoadTimerReset"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DiscordQuestNameShown {
            get {
                return ((bool)(this["DiscordQuestNameShown"]));
            }
            set {
                this["DiscordQuestNameShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DiscordArmorSetShown {
            get {
                return ((bool)(this["DiscordArmorSetShown"]));
            }
            set {
                this["DiscordArmorSetShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableCaravanOverride {
            get {
                return ((bool)(this["EnableCaravanOverride"]));
            }
            set {
                this["EnableCaravanOverride"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableCaravanScore {
            get {
                return ((bool)(this["EnableCaravanScore"]));
            }
            set {
                this["EnableCaravanScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Monster1HealthBarShown {
            get {
                return ((bool)(this["Monster1HealthBarShown"]));
            }
            set {
                this["Monster1HealthBarShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double Monster1HealthBarX {
            get {
                return ((double)(this["Monster1HealthBarX"]));
            }
            set {
                this["Monster1HealthBarX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public double Monster1HealthBarY {
            get {
                return ((double)(this["Monster1HealthBarY"]));
            }
            set {
                this["Monster1HealthBarY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Monster2HealthBarShown {
            get {
                return ((bool)(this["Monster2HealthBarShown"]));
            }
            set {
                this["Monster2HealthBarShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double Monster2HealthBarX {
            get {
                return ((double)(this["Monster2HealthBarX"]));
            }
            set {
                this["Monster2HealthBarX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public double Monster2HealthBarY {
            get {
                return ((double)(this["Monster2HealthBarY"]));
            }
            set {
                this["Monster2HealthBarY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Monster3HealthBarShown {
            get {
                return ((bool)(this["Monster3HealthBarShown"]));
            }
            set {
                this["Monster3HealthBarShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double Monster3HealthBarX {
            get {
                return ((double)(this["Monster3HealthBarX"]));
            }
            set {
                this["Monster3HealthBarX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public double Monster3HealthBarY {
            get {
                return ((double)(this["Monster3HealthBarY"]));
            }
            set {
                this["Monster3HealthBarY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Monster4HealthBarShown {
            get {
                return ((bool)(this["Monster4HealthBarShown"]));
            }
            set {
                this["Monster4HealthBarShown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double Monster4HealthBarX {
            get {
                return ((double)(this["Monster4HealthBarX"]));
            }
            set {
                this["Monster4HealthBarX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("160")]
        public double Monster4HealthBarY {
            get {
                return ((double)(this["Monster4HealthBarY"]));
            }
            set {
                this["Monster4HealthBarY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Code Block")]
        public string TextFormatExport {
            get {
                return ((string)(this["TextFormatExport"]));
            }
            set {
                this["TextFormatExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Male")]
        public string GenderExport {
            get {
                return ((string)(this["GenderExport"]));
            }
            set {
                this["GenderExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GouBoostExport {
            get {
                return ((bool)(this["GouBoostExport"]));
            }
            set {
                this["GouBoostExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("11")]
        public string GSRUnlocksExport {
            get {
                return ((string)(this["GSRUnlocksExport"]));
            }
            set {
                this["GSRUnlocksExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Enable11GSR999 {
            get {
                return ((bool)(this["Enable11GSR999"]));
            }
            set {
                this["Enable11GSR999"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableMetadataExport {
            get {
                return ((bool)(this["EnableMetadataExport"]));
            }
            set {
                this["EnableMetadataExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GearDescriptionExport {
            get {
                return ((string)(this["GearDescriptionExport"]));
            }
            set {
                this["GearDescriptionExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableMap {
            get {
                return ((bool)(this["EnableMap"]));
            }
            set {
                this["EnableMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double MapAreaWidth {
            get {
                return ((double)(this["MapAreaWidth"]));
            }
            set {
                this["MapAreaWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public double MapAreaHeight {
            get {
                return ((double)(this["MapAreaHeight"]));
            }
            set {
                this["MapAreaHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double MapX {
            get {
                return ((double)(this["MapX"]));
            }
            set {
                this["MapX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("410")]
        public double MapY {
            get {
                return ((double)(this["MapY"]));
            }
            set {
                this["MapY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Priority")]
        public string ArmorSkillsInfo {
            get {
                return ((string)(this["ArmorSkillsInfo"]));
            }
            set {
                this["ArmorSkillsInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sword and Shield")]
        public string MotionValuesInfo {
            get {
                return ((string)(this["MotionValuesInfo"]));
            }
            set {
                this["MotionValuesInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sword and Shield")]
        public string WeaponTypeInfo {
            get {
                return ((string)(this["WeaponTypeInfo"]));
            }
            set {
                this["WeaponTypeInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("About")]
        public string GuildOptionInfo {
            get {
                return ((string)(this["GuildOptionInfo"]));
            }
            set {
                this["GuildOptionInfo"] = value;
            }
        }
    }
}
