name: Automate Git Stats

on:
  workflow_dispatch:
  schedule:
      - cron: '0 0 1 */3 *'  # Run every 3 months at 00:00 UTC on the 1st day of the month

jobs:
  run_scripts:
    runs-on: ubuntu-latest
    name: Update Git stats images with the latest commits
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
        
      - name: Check if commit was made by github-actions[bot]
        id: check_last_commit_author
        run: |
          LAST_COMMIT_AUTHOR=$(git log -1 --format="%cn")
          echo "Last commit author: $LAST_COMMIT_AUTHOR"
          if [ "$LAST_COMMIT_AUTHOR" = "github-actions[bot]" ]; then
            echo "Commit made by github-actions[bot]. Cancelling the workflow."
            exit 0
          fi
        shell: bash
      
      - name: Install LuaJIT
        run: |
          sudo apt-get update
          sudo apt-get install -y luajit

      - name: Install Lua development files
        run: |
          sudo apt-get install liblua5.1-dev

      - name: Install LuaRocks
        run : |
          wget https://luarocks.org/releases/luarocks-3.8.0.tar.gz
          tar zxpf luarocks-3.8.0.tar.gz
          cd luarocks-3.8.0
          ./configure --with-lua-include=/usr/include/lua5.1/
          make
          sudo make install

      - name: Install Luarocks rocks
        run: |
          echo "Total rocks to install: "
          wc -l < rocks.txt
          while IFS= read -r rock; do
          sudo luarocks install "$rock"
          done < rocks.txt
        working-directory: ./scripts/dependencies

      - name: Install Python packages
        run: |
          pip install -r ./scripts/dependencies/requirements.txt

      - name: Install Ruby and ruby gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          working-directory: ./scripts/dependencies

      - name: Generate Gemfile.lock
        run: |
          cd ./scripts/dependencies
          bundle config set --local deployment 'true'
          bundle install

      # TODO: Remove?
      - name: Cache Ruby gems
        uses: actions/cache@v3
        with:
          path: ./scripts/dependencies/vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Generate git.txt
        run: |
          mkdir -p ./scripts/input
          git log --numstat > ./scripts/input/git.txt

      - name: Count lines from git.txt
        run: |
          echo "Total lines in git text file: "
          wc -l < ./scripts/input/git.txt

      - name: Anonymize emails
        run: |
          luajit ./rename_emails.lua
        working-directory: ./scripts

      - name: Create git_anonymized.txt artifact
        uses: actions/upload-artifact@v3
        with:
          name: git-text-file
          path: ./scripts/input/git_anonymized.txt
          retention-days: 1

      - name: Remove git.txt
        run: |
          rm ./scripts/input/git.txt

      - run: bundle exec rake
        working-directory: ./scripts/dependencies

      - name: Generate images using Python
        run: |
          cd ./scripts
          python commits_per_hour.py; python commits_per_weekday.py

      - name: Remove git_anonymized.txt
        run: |
            rm ./scripts/input/git_anonymized.txt

      - name: Commit and push changes
        run: |
          git add ./scripts/output/commit_types.png ./scripts/output/commits_over_time.png ./scripts/output/commits_per_day_of_week.png ./scripts/output/commits_per_hour.png
          git commit -m "chore(scripts): update git statistics images"
          git push
