name: Actions Status Discord
on:
  push:
  issues:
  pull_request:
  issue_comment:

jobs:
  actions-status-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Discord about issue and pull request comments
        if: github.event_name == 'issue_comment'
        uses: sarisia/actions-status-discord@v1.10.1-pre.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "`MHF-Z Overlay` Status"
          description: |
            <@937384021527257209> New comment: ${{ github.event.issue.url }}
          image: ${{ secrets.EMBED_IMAGE }}
          color: 0xff435d
          username: GitHub Actions
          avatar_url: ${{ secrets.AVATAR_URL }}

      - name: Notify Discord about new issue
        if: github.event_name == 'issues'
        uses: sarisia/actions-status-discord@v1.10.1-pre.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "`MHF-Z Overlay` Status"
          description: |
            <@937384021527257209> New issue: ${{ github.event.issue.title }}
          image: ${{ secrets.EMBED_IMAGE }}
          color: 0xff435d
          username: GitHub Actions
          avatar_url: ${{ secrets.AVATAR_URL }}
  
      - name: Notify Discord about new pull request
        if: github.event_name == 'pull_request'
        uses: sarisia/actions-status-discord@v1.10.1-pre.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "`MHF-Z Overlay` Status"
          description: |
            <@937384021527257209> New pull request: ${{ github.event.pull_request.title }}
          image: ${{ secrets.EMBED_IMAGE }}
          color: 0xff435d
          username: GitHub Actions
          avatar_url: ${{ secrets.AVATAR_URL }}

      - name: Notify Discord about pushes
        if: github.event_name == 'push'
        uses: sarisia/actions-status-discord@v1.10.1-pre.0
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "`MHF-Z Overlay` Status"
          description: |
            New commit
            Click [here](https://github.com/DorielRivalet/MHFZ_Overlay/blob/main/CHANGELOG.md) to view changelog!
          image: ${{ secrets.EMBED_IMAGE }}
          color: 0xff435d
          username: GitHub Actions
          avatar_url: ${{ secrets.AVATAR_URL }}
